### ISSUE TITLE
Feature Tracker

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/polkadot-dev-cli#1]
- [x] polkadot-dev format (format everything with the correct nightly rust version)
- [x] polkadot-dev lint features (runs [zepter](https://github.com/ggwpez/zepter)) #2 
- [x] polkadot-dev lint (runs format, zepter and checks that the versions are coherent with psvm)
- [x] polkadot-dev version (command to control the version via [psvm](https://github.com/paritytech/psvm))
- [x] polkadot-dev prdoc (generate [prdoc](https://github.com/paritytech/prdoc) with default filled in for all modified crates) #4
- [x] polkadot-dev help contribute (doc only command to print a checklist on how to contribute) #3
- [x] polkadot-dev install (Install required dependencies for polkadot-sdk dev: run the [getting started](https://github.com/paritytech/polkadot-sdk/blob/master/scripts/getting-started.sh) script)

**Comment by mittal-parth** [comment]
Questions:

### `lint` [Zepter]

- What's the default command to be run - is it run or format features (when someone says polkadot-dev-cli lint features)
- Which features are we supporting? All or a few to keep the CLI easier to navigate + what about the unstable ones?
- What should we name lint as since the parent command to run zepter itself is called lint

### `help-contribute`

Any suggestions on the help-contribute checklist? The current description is more like a checklist AFTER someone has made changes. If we are looking to make something that helps them contribute from the start then I think its better to keep that in the polkadot-sdk readme since it involves a lot of links (which won't render neatly on the terminal without external packages installed).

Current description:

```
- [ ] ✅ My PR follows the contribution guidelines and is duly filled.
- [ ] 📜 I have generated a duly filled PRDoc.
- [ ] 🧪 I have added tests that prove my fix is effective or that my feature works (if applicable).
- [ ] 📝 I have made corresponding changes to the documentation (if applicable).
- [ ] 🔍 I have linted and formatted my code properly.
```
