### ISSUE TITLE
Add a contributing checklist

### ISSUE THREAD

**Issue by mittal-parth** [mittal-parth/polkadot-dev-cli#3]
```
- [ ] ✅ My PR follows the contribution guidelines and is duly filled.
- [ ] 📜 I have generated a duly filled PRDoc.
- [ ] 🧪 I have added tests that prove my fix is effective or that my feature works (if applicable).
- [ ] 📝 I have made corresponding changes to the documentation (if applicable).
- [ ] 🔍 I have linted and formatted my code properly.
```

**Comment by mittal-parth** [comment]
Closed by https://github.com/mittal-parth/polkadot-dev-cli/commit/936e77d50aa81d8ae9805479051e07c62259d770
